sudo: false
language: java

jdk:
  - openjdk7
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  # - oraclejdk7  # Unsupported
  - oraclejdk8
  - oraclejdk9
  # - oraclejdk10  # Unsupported - https://www.oracle.com/technetwork/java/javase/eol-135779.html
  - oraclejdk11

matrix:
  allow_failures:
    - jdk: openjdk7  # powermock fails in Java 7, which causes the tests that mock static methods to fail
  include:
    - jdk: openjdk9
      before_install:
        # Java certificate issues can happen according to travis
        # This is mentioned for openjdk10 but we have an issue with openjdk9
        # https://www.deps.co/guides/travis-ci-latest-java/#certificate-issues
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

install:
- echo $JAVA_HOME
- mvn install -Dgpg.skip=true -Dmaven.javadoc.skip=true -DskipTests=true

script:
- mvn test -Dmaven.javadoc.skip=true
