sudo: false
language: java

jdk:
  - openjdk7
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk-ea
  - oraclejdk7
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11

install: 
- echo $JAVA_HOME
- mvn install -Dgpg.skip=true

script: mvn test
