sudo: false
language: java

jdk:
  - openjdk7
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  # - oraclejdk7  # Unsupported
  - oraclejdk8
  - oraclejdk9
  # - oraclejdk10  # Unsupported - https://www.oracle.com/technetwork/java/javase/eol-135779.html
  - oraclejdk11

matrix:
  allow_failures:
    - jdk: openjdk7  # powermock fails in Java 7, which causes the tests that mock static methods to fail

install:
- echo $JAVA_HOME
- mvn install -Dgpg.skip=true -Dmaven.javadoc.skip=true -DskipTests=true

script:
- mvn test -Dmaven.javadoc.skip=true
