sudo: false
language: java

jdk:
  # - openjdk7
  # - openjdk8
  # - openjdk9  # In the matrix
  # - openjdk10
  # - openjdk11
  # - oraclejdk7  # Unsupported
  # - oraclejdk8  # In the matrix
  # - oraclejdk9  # In the matrix
  # - oraclejdk10  # Unsupported - https://www.oracle.com/technetwork/java/javase/eol-135779.html
  # - oraclejdk11

matrix:
  allow_failures:
    - jdk: openjdk7  # powermock fails in Java 7, which causes the tests that mock static methods to fail
  include:
    - name: "oraclejdk8"
      language: generic
      install:
        - eval 'wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3a%2F%2Fwww.oracle.com%2Ftechnetwork%2Fjava%2Fjavase%2Fdownloads%2Fjdk8-downloads-2133151.html; oraclelicense=accept-securebackup-cookie;" "https://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-x64.tar.gz"'
        - tar -xvf jdk-8*
        - sudo mkdir -p /usr/lib/jvm
        - sudo mv ./jdk1.8* /usr/lib/jvm/jdk1.8.0
        - sudo update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/jdk1.8.0/bin/java" 1
        - sudo update-alternatives --install "/usr/bin/javac" "javac" "/usr/lib/jvm/jdk1.8.0/bin/javac" 1
        - sudo update-alternatives --install "/usr/bin/javaws" "javaws" "/usr/lib/jvm/jdk1.8.0/bin/javaws" 1
        - sudo chmod a+x /usr/bin/java
        - sudo chmod a+x /usr/bin/javac
        - sudo chmod a+x /usr/bin/javaws
        - sudo chown -R root:root /usr/lib/jvm/jdk1.8.0
        # - sudo apt-get update
        # - sudo add-apt-repository -y ppa:linuxuprising/java
        # - sudo apt-get update
        # - sudo apt install -y oracle-java8-installer
        # - sudo apt install -y oracle-java8-set-default
    #   before_install:
    #     - rm "${JAVA_HOME}/lib/security/cacerts"
    #     - ln -sf /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    # - jdk: oraclejdk9
    #   before_install:
    #     - rm "${JAVA_HOME}/lib/security/cacerts"
    #     - ln -sf /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

install:
- echo $JAVA_HOME
- mvn install -Dgpg.skip=true -Dmaven.javadoc.skip=true -DskipTests=true

script:
- mvn test -Dmaven.javadoc.skip=true
